### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by hrishik18** [shoaibrayeen/Programmers-Community#1558]
- Error while cloning the repo on VS code
![image](https://user-images.githubusercontent.com/72657744/135716130-3fdcba9d-dce1-491b-8283-473866ae16f3.png)

I am unable to make a clone

**Comment by shoaibrayeen** [comment]
I will check and revert back to you.

**Comment by shoaibrayeen** [comment]
Hi @hrishik18 , You can clone now.
let me know if you still face same issue.
