### ISSUE TITLE
Removal of loop from linked list

### ISSUE THREAD

**Issue by ishika22** [shoaibrayeen/Programmers-Community#1567]
Hi @shoaibrayeen, I am able to see the detection of loop problem in linked list folder. However, removal of loop/cycle is not present as per my knowledge. If you permit, can I raise a PR for removal of loop/cycle from linked list?

**Comment by shoaibrayeen** [comment]
Hi @ishika22, yes you can add A PR in which you can add
- a readMe.md file, explaining the problem 
- a solution file which resolves the problem 
- please read contribution.md file before making PR
- add PR in the same directory

**Comment by shoaibrayeen** [comment]
Hi @ishika22, yes you can add A PR in which you can add
- a readMe.md file, explaining the problem 
- a solution file which resolves the problem 
- please read contribution.md file before making PR
- add PR in the same directory
