### ISSUE TITLE
Undefined name 'n' in solutionByPreeti.py

### ISSUE THREAD

**Issue by cclauss** [shoaibrayeen/Programmers-Community#949]
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./Data Structure/Array Or Vector/Right Rotate An Array By K Elements/solutionByPreeti.py:6:20: F821 undefined name 'n'
    reverse( a, k, n - 1 )
                   ^
```
https://github.com/shoaibrayeen/Programmers-Community/blob/master/Data%20Structure/Array%20Or%20Vector/Right%20Rotate%20An%20Array%20By%20K%20Elements/solutionByPreeti.py#L6

**Comment by shoaibrayeen** [comment]
Resolved
