### ISSUE TITLE
Add benchmarks in readme s

### ISSUE THREAD

**Issue by xkcdjerry** [shoaibrayeen/Programmers-Community#962]
People often wonder which soulcon is faster/better,we can do the by benchmarking each program when sumebody is submiting it by running it agenst a very big data/data set.This can make people pay attention to making their alogthoms better and faster,it can also make a good overview.

**Comment by shoaibrayeen** [comment]
and How do you propose to do that?

**Comment by xkcdjerry** [comment]
I'm not sure,but I have a idea.Take use of the github action,when you create a new section,make a file called tests,like this:

in::5
out::120
.....

**Comment by xkcdjerry** [comment]
(I used in:: and out:: in the exsample,but you can use any unusuale strings)

**Comment by xkcdjerry** [comment]
The action will run the program agenst the tests(ignoring tariling whitespace) and report wrong ansers and the test time,adding a new enry at the end of the readme.md,or the time adding can be done by hand.(This is just an idea,don't know if it will work)(another benifit is that the program is garrentyed bug-free)

**Comment by shoaibrayeen** [comment]
The idea is fine but GitHub won't provide such benefits to the normal users.
Apart from that, people who contribute in the community are mostly beginners.

So It won't be good for them.
But Thanks for the idea. I'll consider them.
